spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  type-aliases-package: com.wind.newStart.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

