

# (1)构建路由地址
#zuul:
#  #只是能排除以Eureka注册的存在的服务，但是zuul本身定于的路由，是否存在运行实例，无法确定
#  #如果访问了不存在的实例，会返回500
#  #ignored-services: "*"  排除所有的Eureka注册的存在的服务
#  prefix: /api  #前缀
#  routes:
#    # 这里可以自定义
#    wind_login:
#      # 匹配的路由规则
#      path: /windLogin/**
#      # 路由的目标服务名
#      serviceId: loginService
#    wind_fegin:
#      # 匹配的路由规则
#      path: /windFegin/**
#      # 路由的目标服务名
#      serviceId: feginService

#(2)
# 关闭使用eureka负载路由
#ribbon:
#  eureka:
#    enabled: false
# 如果不使用eureka的话，需要自己定义路由的那个服务的其他负载服务
#wind_login:
#  ribbon:
#    # 这里写你要路由的demo服务的所有负载服务请求地址，本项目只启动一个，因此只写一个
#    listOfServers: http://localhost:8090/