#Default port is 8761
server:
  port: 8762

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:8762
  server:
    waitTimeInMsWhenSyncEmpty: 5


