spring:
  application:
    name: configuration_service
  cloud:
      config:
        discovery:
          enabled: true
        server:
          encrypt.enabled: false
          git:
            uri: https://github.com/wind814/config-yml
            searchPaths: loginService,feginService,zuulService
            username: wind814
            password: whn8130566
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

