spring:
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

# spring cloud eureka
eureka:
  instance:
    #偏向于IP地址进行注册
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

# spring cloud config
#  cloud:
#    config:
#      enabled: true