spring:
  application:
    name: login_service
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
# spring cloud config
  cloud:
    config:
      enabled: true
# spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/