spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

#  serverTimezone=UTC 不加会因为时区问题报错
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wind_0415?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: SZenHj3wx/y1Y1VsifLudNvi9PRb6PLA6/BFyYCA2QtgeBgkcwlF9qkLi3pR82yUT1FY0I1aCAM/TvAMZK3Tbw==
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          decrypt: true
mybatis:
  type-aliases-package: com.wind.newStart.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

dataSource:
  config:
    decrypt: true