spring:
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

# spring cloud eureka
eureka:
  instance:
    #偏向于IP地址进行注册
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

# spring cloud config
#  cloud:
#    config:
#      enabled: true


# (1)构建路由地址
zuul:
  routes:
    # 这里可以自定义
    wind_login:
      # 匹配的路由规则
      path: /windLogin/**
      # 路由的目标服务名
      serviceId: loginService

#(2)
# 关闭使用eureka负载路由
#ribbon:
#  eureka:
#    enabled: false
# 如果不使用eureka的话，需要自己定义路由的那个服务的其他负载服务
#wind_login:
#  ribbon:
#    # 这里写你要路由的demo服务的所有负载服务请求地址，本项目只启动一个，因此只写一个
#    listOfServers: http://localhost:8090/